

- project:
    name: docker-jenkins-pipeline-build-step
    version: 0.0.4-dev # docker-jenkins

    jobs:
      - docker-jenkins-pipeline-build-step:
          version: '{version}'


- job-template:
    name: docker-jenkins-pipeline-build-step

    description: |
      <p>Building Jenkins-Server/Slave Docker-Jenkins CI Pipeline (inits)</p>

      <p>(JTB/{version} .jjb-pipeline-build-step.yml, dev branch)</p>

    project-type: freestyle

    disabled: true

    parameters:

    - choice:
        name: Build_Version
        choices:
        - ""
        - "2.7.3"
        - "2.7.2"
        - "2.7.1"
        - "2.3"
        - "2.0"
        - "1.651.1"
        - "1.565.3"

    - choice:
        name: Build_Tag
        choices:
        - "dev"
        - "latest"
        - "auto"
        - "build"

    - bool:
        name: Rebuild
        default: False
        description: |
          TODO: remove images (and its layers) if they exist?

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 


    # JJB 1.5.1
    builders:
    - dsl:
        targets: .Jenkinsfile
        ignore-existing: "true"
        removed-job-action: "DISABLE"
        removed-view-action: "DELETE"
        lookup-strategy: "SEED_JOB"
        additional-classpath: "*.jar" 

    scm:
    - git:
        url: https://github.com/dotmpe/docker-jenkins.git
        #url: git@github.com:dotmpe/docker-jenkins.git
        branches:
        - origin/dev
        local-branch: dev
        skip-tag: true
        wipe-workspace: true

#    dsl:
#      # FIXME: github:dotmpe/jenkins-jobs-builder #f_pipeline_dsl
#      #dsl-file: .Jenkinsfile
#      #needs-workspace: true
#
#      script-name: .Jenkinsfile
#
#      scm:
#      - git:
#          url: https://github.com/dotmpe/docker-jenkins.git
#          #url: git@github.com:dotmpe/docker-jenkins.git
#          branches:
#          - origin/f_ci_pipeline
#          local-branch: f_ci_pipeline
#          skip-tag: true
#          wipe-workspace: true


