

- project:
    name: docker-jenkins-dry-run-pipeline
    version: 0.0.4-dev # docker-jenkins
    file: .jjb-docker-dry-run.yml

    jobs:
      - '{name}-dry-run-pipeline':
          description: |
            <p>Testing Docker-Jenkins CI Pipeline interacting with docker daemon. </p>

            <p><code class="muted">{name}/{version} {file}</code></p>



- job-template:
    name: '{name}-dry-run-pipeline'

    project-type: workflow

    metadata:
    - string:
        name: DCKR_JNK_VERSION
        value: '{version}'
        expose-to-env: true
    - string:
        name: DCKR_JNK_JJB_FILE
        value: '{file}'
        expose-to-env: true

    parameters: []

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 

    dsl:
      script: |

        stage "Prerun"
        println "Waiting for node 'dind || docker-host'"
        node("dind || docker-host") {

          stage "Docker Dry-Run"
          sh 'docker info'
          sh 'docker ps'
        }


