
- job:
    name: docker-jenkins-dry-run-pipeline
    version: 0.0.2 # docker-jenkins

    description: |
      Testing Docker-Jenkins CI Pipeline

    project-type: workflow

    parameters: []

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 

    dsl:
      script: |

        stage "Prerun"
        println "Waiting for node 'dind || docker-host'"
        node("dind || docker-host") {

          stage "Docker Dry-Run"
          sh 'docker info'
          sh 'docker ps'
        }


