
- job:
    name: docker-jenkins-dry-run-pipeline
    version: 0.0.4-dev # docker-jenkins

    description: |
      Testing Docker-Jenkins CI Pipeline interacting with docker daemon.

      <p>(JTB/{version} .jjb-docker-dry-run.yml)</p>

    project-type: workflow

    parameters: []

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 

    dsl:
      script: |

        stage "Prerun"
        println "Waiting for node 'dind || docker-host'"
        node("dind || docker-host") {

          stage "Docker Dry-Run"
          sh 'docker info'
          sh 'docker ps'
        }


