

- project:
    name: docker-jenkins
    version: 0.0.5-dev # docker-jenkins
    file: .jjb-pipeline-build-step.yml

    jobs:
      - '{name}-pipeline-build-step': {}



- job-template:
    name: '{name}-pipeline-build-step'

    project-type: freestyle

    disabled: true

    description: |
      <p>Building Jenkins-Server/Slave Docker-Jenkins (<code class="muted">inits.sh</code>) in a pipeline build-step. </p>

      <p><code class="muted">{name}/{version}</code> <code class="muted">{file}</code></p>

      <ul>
        <li>XXX: dsl build-step does not accept a dotfile path</li>
        <li>FIXME: Jenkinsfile does not see Build_Tag env param in build-step plugin</li>
      </ul>

    parameters:

    - hidden:
        name: DCKR_JNK_VERSION
        default: '{version}'
    - hidden:
        name: DCKR_JNK_JJB_FILE
        default: '{file}'

    - choice:
        name: Build_Tag
        choices:
        - ""
        - "2.7.4"
        - "2.7.3"
        - "2.7.2"
        - "2.7.1"
        - "2.3"
        - "2.0"
        - "1.651.1"
        - "1.565.3"

    - choice:
        name: Build_Env
        choices:
        - "build"
        - "latest"
        - "auto"
        - "dev"

    - bool:
        name: Rebuild
        default: False
        description: |
          TODO: remove images (and its layers) if they exist?

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 

    builders:
    - shell:
        ln -s .Jenkinsfile Jenkinsfile
    - dsl:
        targets: Jenkinsfile
        ignore-existing: "true"
        removed-job-action: "DISABLE"
        removed-view-action: "DELETE"
        lookup-strategy: "SEED_JOB"
        additional-classpath: "*.jar" 

    scm:
    - git:
        url: https://github.com/dotmpe/docker-jenkins.git
        branches:
        - origin/dev
        local-branch: dev
        skip-tag: true
        wipe-workspace: true

