

- project:
    name: docker-jenkins
    version: 0.0.4-dev # docker-jenkins
    file: .jjb-docker-dry-run.yml

    jobs:
      - '{name}-dry-run-pipeline': {}



- job-template:
    name: '{name}-dry-run-pipeline'

    project-type: workflow

    description: |
      <p>Testing Docker-Jenkins CI Pipeline interacting with docker daemon. </p>

      <p><code class="muted">{name}/{version}</code> <code class="muted">{file}</code></p>


    parameters: []

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 

    dsl:
      script: |

        withEnv([
          "DCKR_JNK_VERSION={version}",
          "DCKR_JNK_JJB_FILE={file}"
        ]) {{

          stage("DinD wait") {{
            println "Waiting for node 'dind || docker-host'"
          }}

          node("dind || docker-host") {{

            stage("Env") {{
              sh 'env | grep DCKR_JNK'
            }}

            stage("Docker Dry-Run") {{
              sh 'docker info'
              sh 'docker ps'
            }}
          }}
        }}


