

- project:
    name: docker-jenkins
    version: 0.0.4-dev # docker-jenkins
    file: .jjb-pipeline-build-step.yml

    jobs:
      - '{name}-pipeline-build-step':
          description: |
            <p>Building Jenkins-Server/Slave Docker-Jenkins CI Pipeline (inits)</p>

            <p><code class="muted">{name}/{version} {file}</code></p>



- job-template:
    name: '{name}-pipeline-build-step'

    project-type: freestyle

    disabled: true

    metadata:
    - string:
        name: DCKR_JNK_VERSION
        value: '{version}'
        expose-to-env: true
    - string:
        name: DCKR_JNK_JJB_FILE
        value: '{file}'
        expose-to-env: true

    parameters:

    - choice:
        name: Build_Tag
        choices:
        - ""
        - "2.7.4"
        - "2.7.3"
        - "2.7.2"
        - "2.7.1"
        - "2.3"
        - "2.0"
        - "1.651.1"
        - "1.565.3"

    - choice:
        name: Build_Env
        choices:
        - "build"
        - "latest"
        - "auto"
        - "dev"

    - bool:
        name: Rebuild
        default: False
        description: |
          TODO: remove images (and its layers) if they exist?

    triggers:
    - pollscm:
        cron: "*/1 * * * *" 


    # JJB 1.5.1
    builders:
    - dsl:
        targets: .Jenkinsfile
        ignore-existing: "true"
        removed-job-action: "DISABLE"
        removed-view-action: "DELETE"
        lookup-strategy: "SEED_JOB"
        additional-classpath: "*.jar" 

    scm:
    - git:
        url: https://github.com/dotmpe/docker-jenkins.git
        branches:
        - origin/dev
        local-branch: dev
        skip-tag: true
        wipe-workspace: true

#    dsl:
#      # FIXME: github:dotmpe/jenkins-jobs-builder #f_pipeline_dsl
#      #dsl-file: .Jenkinsfile
#      #needs-workspace: true
#
#      script-name: .Jenkinsfile
#
#      scm:
#      - git:
#          url: https://github.com/dotmpe/docker-jenkins.git
#          #url: git@github.com:dotmpe/docker-jenkins.git
#          branches:
#          - origin/f_ci_pipeline
#          local-branch: f_ci_pipeline
#          skip-tag: true
#          wipe-workspace: true


