

- name: docker-jenkins
  id: docker-jenkins
  main: docker-jenkins
    
  environments:
  - dev
  - acc
  - prod

  environment:
    dev:
      - Build_Deps_Default_Paths=1
      - sudo=

  pd-meta:
    env: dev
    tasks:
      tags:
        - XXX
        - TODO
        - FIXME
        - TOTEST

